name: Nombrecito del workflow

on:
  push: 
    branches:
      - main

jobs:
  hello_world:
    runs-on: ubuntu-22.04
    steps: 
      - name: Mostrar mensaje
        run: |
          echo "Hola"
          echo "Adiós"
      - name: Mostrar fecha
        run: date
      - run: ls -l
